version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_USERNAME=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASS}  
      - MONGO_CLUSTER=${MONGO_CLUSTER}
      - MONGO_DB=${MONGO_DB}
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  